Updates to oep-0025-proc-incremental-improvements.rst
edx/open-edx-proposals pull request #168
Opened 2020-11-13 16:10 UTC by michellephilbrick

Looking for reviews/feedback on the TL;DR section added at the beginning!

2020-11-13 16:24 UTC, nedbat requested changes

2020-11-13 16:24 UTC, nedbat commented on oeps/oep-0025-proc-incremental-improvements.rst
> +=====
Very minor nit: headings read better in the file if you leave a blank line after them.

2020-11-13 16:24 UTC, nedbat commented on oeps/oep-0025-proc-incremental-improvements.rst
> +* Tickets must meet the requirements for the INCR Jira project outlined in the `Specification`_ section of this document
These bullets should end with a period.

2020-11-13 16:24 UTC, nedbat commented on oeps/oep-0025-proc-incremental-improvements.rst
> +* INCR tickets should only be written for the parts of the project for which they are appropriate (those that can realistically be broken into smaller tasks and don’t require more extensive knowledge
This is missing a closing paren.

2020-11-13 16:24 UTC, nedbat commented on oeps/oep-0025-proc-incremental-improvements.rst
> +* Work on INCR tickets can be done by (but not limited to): Developers (experienced with Open edX or wanting more experience, computer programming students, hackathon teams, new edX technical employe
Was this meant to be a longer list? It only has "Developers" in it now.  It's also missing a closing paren.

2020-11-18 20:50 UTC, merged

2020-11-18 23:43 UTC, nasthagiri commented
Congratulations on your first PR!

![](https://media3.giphy.com/media/fxsqOYnIMEefC/giphy.gif)